// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// pad_matrix_with_zeros
arma::mat pad_matrix_with_zeros(arma::mat x, int d);
RcppExport SEXP FastSC3_pad_matrix_with_zeros(SEXP xSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    __result = Rcpp::wrap(pad_matrix_with_zeros(x, d));
    return __result;
END_RCPP
}
// constr_P
arma::mat constr_P(int p, int k, int d, int n);
RcppExport SEXP FastSC3_constr_P(SEXP pSEXP, SEXP kSEXP, SEXP dSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(constr_P(p, k, d, n));
    return __result;
END_RCPP
}
// constr_H
arma::mat constr_H(int d);
RcppExport SEXP FastSC3_constr_H(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    __result = Rcpp::wrap(constr_H(d));
    return __result;
END_RCPP
}
// constr_D
arma::rowvec constr_D(int d);
RcppExport SEXP FastSC3_constr_D(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    __result = Rcpp::wrap(constr_D(d));
    return __result;
END_RCPP
}
// calc_fjlt
arma::mat calc_fjlt(arma::mat x, int p, int k, int d, int n);
RcppExport SEXP FastSC3_calc_fjlt(SEXP xSEXP, SEXP pSEXP, SEXP kSEXP, SEXP dSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(calc_fjlt(x, p, k, d, n));
    return __result;
END_RCPP
}
// calc_delta
double calc_delta(arma::mat K, int k);
RcppExport SEXP FastSC3_calc_delta(SEXP KSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    __result = Rcpp::wrap(calc_delta(K, k));
    return __result;
END_RCPP
}
// ssNystrom
arma::mat ssNystrom(arma::mat K, int c);
RcppExport SEXP FastSC3_ssNystrom(SEXP KSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type c(cSEXP);
    __result = Rcpp::wrap(ssNystrom(K, c));
    return __result;
END_RCPP
}
