# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Construct the P matrix for the FJLT transform
#' 
#' @param epsilon error tolerance parameter
#' @param p the norm
#' @param k dimension we reduce to
#' @param d dimension of the input matrix
#' @param n number of cells (columns) in the input matrix
#' 
#' @return matrix P of the FJLT transform
#' 
constructP <- function(p, k, d, n) {
    .Call('FastSC3_constructP', PACKAGE = 'FastSC3', p, k, d, n)
}

#' Construct the H (Hadamard) matrix for the FJLT transform
#' 
#' @param d dimension of the input matrix
#' 
#' @return matrix H of the FJLT transform
#' 
constructH <- function(d) {
    .Call('FastSC3_constructH', PACKAGE = 'FastSC3', d)
}

#' Construct the D matrix for the FJLT transform
#' 
#' @param d dimension of the input matrix
#' 
#' @return matrix D of the FJLT transform
#' 
constructD <- function(d) {
    .Call('FastSC3_constructD', PACKAGE = 'FastSC3', d)
}

#' Calculate the FJLT transform
#' 
#' Fast-Johnson-Lindenstrauss-Transform
#' 
#' @param epsilon error tolerance parameter
#' @param p the norm
#' @param k dimension we reduce to
#' @param d dimension of the input matrix
#' @param n number of cells (columns) in the input matrix
#' 
#' @return FJLT transform
#' 
calculateFJLT <- function(x, p, k, d, n) {
    .Call('FastSC3_calculateFJLT', PACKAGE = 'FastSC3', x, p, k, d, n)
}

