# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the FJLT transform
#' 
#' Fast-Johnson-Lindenstrauss-Transform
#' 
#' @param x input matrix
#' @param d dimension to pad to
#' 
#' @return FJLT transform
#' 
pad_matrix_with_zeros <- function(x, d) {
    .Call('FastSC3_pad_matrix_with_zeros', PACKAGE = 'FastSC3', x, d)
}

#' Construct the P matrix for the FJLT transform
#' 
#' @param epsilon error tolerance parameter
#' @param p the norm
#' @param k dimension we reduce to
#' @param d dimension of the input matrix
#' @param n number of cells (columns) in the input matrix
#' 
#' @return matrix P of the FJLT transform
#' 
constr_P <- function(p, k, d, n) {
    .Call('FastSC3_constr_P', PACKAGE = 'FastSC3', p, k, d, n)
}

#' Construct the H (Hadamard) matrix for the FJLT transform
#' 
#' @param d dimension of the input matrix
#' 
#' @return matrix H of the FJLT transform
#' 
constr_H <- function(d) {
    .Call('FastSC3_constr_H', PACKAGE = 'FastSC3', d)
}

#' Construct the D matrix for the FJLT transform
#' 
#' @param d dimension of the input matrix
#' 
#' @return matrix D of the FJLT transform
#' 
constr_D <- function(d) {
    .Call('FastSC3_constr_D', PACKAGE = 'FastSC3', d)
}

#' Calculate the FJLT transform
#' 
#' Fast-Johnson-Lindenstrauss-Transform
#' 
#' @param x matrix to be transformed
#' @param p the norm
#' @param k dimension we reduce to
#' @param d dimension of the input matrix
#' @param n number of cells (columns) in the input matrix
#' 
#' @return FJLT transform
#' 
calc_fjlt <- function(x, p, k, d, n) {
    .Call('FastSC3_calc_fjlt', PACKAGE = 'FastSC3', x, p, k, d, n)
}

calculate_P1 <- function(X) {
    .Call('FastSC3_calculate_P1', PACKAGE = 'FastSC3', X)
}

normalise_kernel <- function(K) {
    .Call('FastSC3_normalise_kernel', PACKAGE = 'FastSC3', K)
}

calc_delta <- function(K, k) {
    .Call('FastSC3_calc_delta', PACKAGE = 'FastSC3', K, k)
}

#' Calculate approximate eigenvectors
#' 
#' Nystrom spectral shifting method
#' 
#' @param K input SPSD matrix
#' @param c number of selected columns as fraction of ncol(K)
#' 
#' @return approximate eigenvectors
#' 
ssNystrom <- function(K, c) {
    .Call('FastSC3_ssNystrom', PACKAGE = 'FastSC3', K, c)
}

